name: Deploy Mosquitto

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/Hamadiwolf/mosquitto:latest

      - name: Deploy to GitHub Container Registry
        run: echo ::set-output name=image::ghcr.io/Hamadiwolf/mosquitto:latest
        id: docker
